### ISSUE TITLE
Issue #13: Add Card Hover Effects

### ISSUE THREAD

**Issue by MehulPardeshi** [Swifty9/Maverick-AI#58]
**Description**:
Add subtle hover animations to card components to improve user interaction feedback.

**Tasks**:
- [x] Create hover animations
- [x] Add shadow effects
- [x] Implement scale transition
- [x] Add content hover states
- [x] Ensure accessibility

**Technical Requirements**:
- CSS transitions
- Tailwind CSS
- Basic animation principles

**Acceptance Criteria**:
- Smooth hover effects
- Consistent animations
- Accessible interactions
- Performance optimization

**Comment by TheMercury1229** [comment]
Hey can u assign this issue to me

**Comment by Jayesh-Kr** [comment]
Hi @MehulPardeshi, I would like to work on this issue. Could you please assign it to me. Thanks!

**Comment by MehulPardeshi** [comment]
> Hi @MehulPardeshi, I would like to work on this issue. Could you please assign it to me. Thanks!

Keep us posted on your progress here. Also while making any PRs, do check out the [CONTRIBUTING.md](https://github.com/Swifty9/Maverick-AI/blob/main/CONTRIBUTING.md) for rules for contribution

**Comment by Jayesh-Kr** [comment]
@MehulPardeshi I have added effect on cards on hovering and added some animation too. But I am facing problem while running  npm run format as told in CONTRIBUTING.md

**Comment by divyesh-mali** [comment]
> @MehulPardeshi I have added effect on cards on hovering and added some animation too. But I am facing problem while running  npm run format as told in CONTRIBUTING.md and also can you provide me something from where I can learn to test

Try to run with docker. It should work. The steps are given readme file.

**Comment by divyesh-mali** [comment]
Steps to run with Docker steps are given in  readme file.

**Comment by Siddheshuncodes** [comment]
@Jayesh-Kr if you have used Yarn it won't work

This project was built using npm so to get started I would suggest you start with 

npm install 

and then 

npm run dev

If you are still facing any issues or problems please add relevant screenshots so that we can better understand your problem.

**Comment by Jayesh-Kr** [comment]
@Siddheshuncodes I have setup the project and added the functionality. But now according to code guidelines we have to do 
npm run lint
npm run format
I am not able to run "npm run format"
![image](https://github.com/user-attachments/assets/1ff1be48-3936-4236-9001-b81e86c9e6ee)
I have formatted the code with prettier. If you say I will create a pull request

**Comment by Siddheshuncodes** [comment]
You are using the wrong command here

Try using --> npm run dev

**Comment by Siddheshuncodes** [comment]
if you are still facing any errors then ping me again we will look into it
